### ISSUE TITLE
Unable to install on windows 10

### ISSUE THREAD

**Issue by VishalWaman** [jduncanator/node-diskusage#25]
> 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! diskusage@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the diskusage@0.2.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

Thanks in advance, this is in electronJS app

**Comment by jduncanator** [comment]
I can't do much with that level of logging (there isn't even an error message in that log). Are you able to provide the full npm logs for the entire operation?

**Comment by adamelliotfields** [comment]
@VishalWaman - it works, you just need to make sure `node-gyp` can build in your environment.

Here's my setup.

1. Install Microsoft Visual Studio Community 2017: <https://www.visualstudio.com/downloads>

2. In Visual Studio Installer, you need to install the following *Individual components* (hint: they are in the tab titled "Individual components"):
    - Static analysis tools (required by VC++ toolset)
    - Visual Studio C++ core features
    - VC++ 2017 v141 toolset (x86,x64)
    - Windows 10 SDK (10.0.14393.0)

3. Install Python 2: <https://www.python.org/downloads/release/python-2714>

4. Create a `.npmrc` in your home directory (`C:\Users\Vishal`) with the following content:

```
msvs_version=2017
python=C:\Python27\python.exe
```

You should be good to go. To debug `node-gyp`, just create a new project and `npm install node-gyp` then run `.\node_modules\.bin\node-gyp configure --verbose` from within your new project directory.

You should see

```
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import platform; print(platform.python_version());"` returned: "2.7.14\r\n"
```

and

```
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.14393
gyp verb find vs2017   - Using this installation with Windows 10 SDK
```

Hopefully this helps steer you in the right direction. If you still have issues, feel free to ask, otherwise, close the issue :)

**Comment by jduncanator** [comment]
Thanks to @adamelliotfields's for the extra information. I'll close this issue now.

@VishalWaman If you are still encountering this issue, and have any more information for me, feel free to leave a reply and I'll re-open the issue and take a look.
