### ISSUE TITLE
Function definition wrong

### ISSUE THREAD

**Issue by NINI1988** [jduncanator/node-diskusage#27]
If an error occured the result is undefined.

Definition:
`export function check(path: string, callback: (error: Error, result: DiskUsage) => void): void;`

Should be:
`export function check(path: string, callback: (error?: Error, result?: DiskUsage) => void): void;`

The question marks behind error and result helps in typescript to avoid access to undefined varibles.

Thanks for providing this module :-)

**Comment by jduncanator** [comment]
I'll update the module this week to include the correct function definition, I'm assuming this is a non-breaking change?

Thanks!

**Comment by NINI1988** [comment]
Yes, its an non-bracking change.

**Comment by jduncanator** [comment]
I'm closing this because I don't think changing these to optional parameters is the right move to make. Neither is really incorrect, however the TypeScript documentation leans towards having optional parameters, in a scenario like this, in a callback as being an anti-pattern.

Given this has next to no benefit to end users, it's easier to just close this.

If anyone has an actual use case where they need the parameters defined as optional in the TypeScript definition, leave a comment here and I'll reconsider.

**Comment by NINI1988** [comment]
This is actual an error. When an error occure the result is undefined. When you then access result you will get an "access to undefined" error. When this parameter is set to optional and you activate strictNullChecks in typescript the compiler will warn you about this access.
There are two sollutions:
- Set this argument as optional
- Or allways return a DiskUsage object in result and never return undefined.

**Comment by jduncanator** [comment]
As per the examples, and nearly every other callback in nodejs fs module, you should be checking if error or result is undefined before accessing either.

I’ll take a look at the typescript definitions of the fs module and aim to replicate that.

**Comment by NINI1988** [comment]
So when it can be undefined, why not specifieing the interface correctly? You could also write `result:Diskusage|undefined` which is the same as question mark.
